# Generated by Django 3.1.7 on 2021-02-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_form', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='date',
        ),
        migrations.AddField(
            model_name='booking',
            name='day',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.CharField(max_length=20),
        ),
    ]
