# Generated by Django 3.1.7 on 2021-02-24 17:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_form', '0002_auto_20210224_1311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='phone',
            new_name='number',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='day',
        ),
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.DateField(default=datetime.date(2021, 2, 24)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='booking',
            name='message',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='booking',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='surname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.TimeField(),
        ),
    ]
