# Generated by Django 3.1.7 on 2021-02-24 17:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_form', '0004_auto_20210224_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.TimeField(default=datetime.datetime(2021, 2, 24, 9, 0)),
        ),
    ]
