# Generated by Django 3.1.7 on 2021-02-24 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_form', '0005_auto_20210224_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.TimeField(),
        ),
    ]
