# Generated by Django 3.1.7 on 2021-02-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_form', '0007_auto_20210224_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_free',
            field=models.BooleanField(default=True),
        ),
    ]
