# Generated by Django 3.1.7 on 2022-02-02 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_form', '0008_booking_is_free'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='surname',
        ),
        migrations.AlterField(
            model_name='booking',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
