# Generated by Django 3.1.7 on 2021-02-28 14:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contactme_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactme',
            name='date',
            field=models.DateField(default=datetime.date(2021, 2, 28)),
        ),
    ]
