# Generated by Django 3.1.7 on 2021-03-01 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20210228_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactme',
            name='date',
            field=models.DateField(default=datetime.date(2021, 3, 1)),
        ),
    ]
