# Generated by Django 3.1.7 on 2021-03-01 11:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20210301_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactme',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 3, 1, 11, 56, 47, 279345, tzinfo=utc)),
        ),
    ]
