# Generated by Django 3.1.7 on 2021-03-01 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_auto_20210301_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactme',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
