# Generated by Django 3.1.7 on 2022-02-07 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_auto_20210301_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactme',
            name='surname',
        ),
        migrations.AlterField(
            model_name='contactme',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
