# Generated by Django 3.1.7 on 2021-03-01 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biography',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('specialization', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('nationality', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=50)),
                ('summary', models.TextField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(default='Present')),
                ('position', models.CharField(max_length=150)),
                ('position_summary', models.CharField(max_length=1000)),
                ('biography', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biography.biography')),
            ],
        ),
        migrations.CreateModel(
            name='Responsibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsibility', models.CharField(max_length=1000)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biography.workexperience')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=150)),
                ('topic_summary', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=100)),
                ('biography', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biography.biography')),
            ],
        ),
        migrations.CreateModel(
            name='Passions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passion', models.CharField(max_length=100)),
                ('biography', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biography.biography')),
            ],
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=50)),
                ('fluency', models.CharField(max_length=50)),
                ('biography', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biography.biography')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(default='Present')),
                ('name_of_institution', models.CharField(max_length=300)),
                ('biography', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biography.biography')),
            ],
        ),
        migrations.CreateModel(
            name='CoveredSubjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biography.education')),
            ],
        ),
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accomplishment', models.CharField(max_length=500)),
                ('biography', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biography.biography')),
            ],
        ),
    ]
