# Generated by Django 3.1.7 on 2021-03-01 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biography', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsibility',
            name='job',
        ),
        migrations.AddField(
            model_name='education',
            name='covered_subjects',
            field=models.CharField(default=None, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workexperience',
            name='responsibilities',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CoveredSubjects',
        ),
        migrations.DeleteModel(
            name='Responsibility',
        ),
    ]
