# Generated by Django 3.1.7 on 2021-03-01 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biography', '0002_auto_20210301_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievements',
            name='accomplishment',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='education',
            name='covered_subjects',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='personalexperience',
            name='topic_summary',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='position_summary',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='responsibilities',
            field=models.TextField(max_length=2000),
        ),
    ]
