# Generated by Django 3.1.7 on 2021-03-01 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biography', '0005_auto_20210301_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='speciality',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
