# Generated by Django 3.1.7 on 2022-02-07 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biography', '0009_auto_20220207_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='biography',
            name='academic_achievements_title',
            field=models.CharField(default='Academic Achievements Title', max_length=255),
        ),
        migrations.AddField(
            model_name='biography',
            name='childhood_title',
            field=models.CharField(default='Childhood Title', max_length=255),
        ),
        migrations.AddField(
            model_name='biography',
            name='final_thoughts_title',
            field=models.CharField(default='Final Thoughts Title', max_length=255),
        ),
        migrations.AddField(
            model_name='biography',
            name='summary_title',
            field=models.CharField(default='Summary Title', max_length=255),
        ),
    ]
