# Generated by Django 3.1.7 on 2021-02-23 13:02

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('video_gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='url',
        ),
        migrations.AddField(
            model_name='video',
            name='video_url',
            field=embed_video.fields.EmbedVideoField(default='https://www.youtube.com/'),
        ),
    ]
