# Generated by Django 3.1.7 on 2021-02-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture_gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='photo',
            field=models.ImageField(upload_to='images'),
        ),
    ]
