# Generated by Django 3.1.7 on 2021-02-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
