# Generated by Django 3.1.7 on 2021-02-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0002_auto_20210226_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='location',
            field=models.CharField(max_length=500),
        ),
    ]
